services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_CONN=mongodb://mongo:27017
      - ACCESS_KEY=dev_access_secret_key_123456789
      - REFRESH_KEY=dev_refresh_secret_key_987654321
    depends_on:
      - mongo

volumes:
  # postgres_data:
  mongo_data:
