definitions:
  auth.LoginDto:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  auth.TokenDto:
    properties:
      accessToken:
        type: string
    type: object
  info.ServerInfoDto:
    properties:
      build:
        type: string
      buildTimestamp:
        type: string
      commitHash:
        type: string
      version:
        type: string
    type: object
  user.NewUserDto:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        enum:
        - admin
        - user
        type: string
      username:
        maxLength: 100
        minLength: 2
        type: string
      uuid:
        type: string
    required:
    - password
    - role
    - username
    type: object
  user.UserDto:
    properties:
      email:
        type: string
      policeToken:
        type: string
      role:
        type: string
      username:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: loginDto
        required: true
        schema:
          $ref: '#/definitions/auth.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenDto'
      summary: User login
      tags:
      - auth
  /auth/logout:
    post:
      description: Logs out current user session
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: User Logout
      tags:
      - auth
  /auth/refresh:
    post:
      description: Generates a new access token using a valid refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenDto'
      summary: Refresh Access Token
      tags:
      - auth
  /info:
    get:
      description: return information about the server build, version, etc ...
      produces:
      - application/json
      responses:
        "200":
          description: Information about server
          schema:
            $ref: '#/definitions/info.ServerInfoDto'
      summary: Get server info
      tags:
      - info
  /user:
    post:
      parameters:
      - description: Data for new user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/user.NewUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create new user
      tags:
      - user
  /user/{uuid}:
    delete:
      description: delete a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: delete user with uuid
      tags:
      - user
    get:
      description: get a user with uuid
      parameters:
      - description: user uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: get user with uuid
      tags:
      - user
    put:
      parameters:
      - description: uuid of user to be updated
        in: path
        name: uuid
        required: true
        type: string
      - description: Data for updating user
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/user.UserDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update user with new dat
      tags:
      - user
  /user/all-users:
    get:
      description: Fetches all users for admin
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserDto'
            type: array
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Get all users for admin
      tags:
      - user
  /user/my-data:
    get:
      description: Fetches the currently logged-in user's data based on the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get logged-in user data
      tags:
      - user
  /user/search:
    get:
      description: Performs a fuzzy search for users by first name, last name, or
        full name with similarity matching
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserDto'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Search users by name
      tags:
      - user
swagger: "2.0"
